// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWQWij4I5qJHdt-a7-liGJID2PeLAeShQ',
    appId: '1:354418938883:web:ff6739158f3d3eeb6caa36',
    messagingSenderId: '354418938883',
    projectId: 'smarthome-d1c03',
    authDomain: 'smarthome-d1c03.firebaseapp.com',
    storageBucket: 'smarthome-d1c03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg_Q1bLFeV-C1iRR27pu0nAvROvA3toHw',
    appId: '1:354418938883:android:2df394f416bff5376caa36',
    messagingSenderId: '354418938883',
    projectId: 'smarthome-d1c03',
    storageBucket: 'smarthome-d1c03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb4Nl94zDZoEfq8GuRiW4BiozTCmFMNos',
    appId: '1:354418938883:ios:819d085b640ef1e06caa36',
    messagingSenderId: '354418938883',
    projectId: 'smarthome-d1c03',
    storageBucket: 'smarthome-d1c03.appspot.com',
    iosClientId: '354418938883-oue9f5oi00k5vnje8huaif3lhjb2tnie.apps.googleusercontent.com',
    iosBundleId: 'com.example.homecontroller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb4Nl94zDZoEfq8GuRiW4BiozTCmFMNos',
    appId: '1:354418938883:ios:40973dbfb32518cc6caa36',
    messagingSenderId: '354418938883',
    projectId: 'smarthome-d1c03',
    storageBucket: 'smarthome-d1c03.appspot.com',
    iosClientId: '354418938883-vj7fc9uchc8f605f8n8edgngea4acdbq.apps.googleusercontent.com',
    iosBundleId: 'cloud.perz.client',
  );
}
