name: Platform Tests
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test Platform .NET
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 5.0.x    
      - name: Install dependencies
        run: dotnet restore ./platform/IoTPlatform.sln
      - name: Dotnet Test
        run: dotnet test --no-restore --no-build ./platform/IoTPlatform.sln