name: Publish Hub Images
on:
  push:
    branches:
      - master
jobs:
  publish-x86:
    name: Publish x86 Docker Image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          file: ./platform/docker/Hub.x86.Dockerfile
          context: ./platform
          push: true
          tags: ghcr.io/maperz/iot-hub
  publish-arm:
    name: Publish ARM Docker Image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          file: ./platform/docker/Hub.Arm.Dockerfile
          context: ./platform
          push: true
          tags: ghcr.io/maperz/iot-hub/arm
