name: Publish client
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.2'
      - name: Install pub dependencies
        run: flutter pub get
        working-directory: client
      - name: Run flutter tests
        run: flutter test
        working-directory: client
      - name: Build Web Application
        working-directory: client
        run: flutter build web
      - name: Deploy Web Application to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SMARTHOME_D1C03 }}'
          channelId: live
          projectId: smarthome-d1c03
      - name: Build Android APK
        working-directory: client
        run: flutter build apk
      - name: Build MacOS
        working-directory: client
        run: flutter config --enable-macos-desktop && flutter build macos 
      - name: Upload to github release 
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "HomeController APK"
          files: |
            client/build/macos/Build/Products/Release/HomeController.app 
            client/build/app/outputs/flutter-apk/app-release.apk