name: Publish Server Images
on:
  push:
    branches:
      - master
    paths:
      - "platform/**"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
  build:
    needs: setup
    steps:
      - name: Build platform
        run: dotnet build ./platform/IoTPlatform.sln
  test:
    needs: build
    steps:
      - name: Run dotnet platform tests
        run: dotnet test ./platform/IoTPlatform.sln

  publish-x86:
    needs: test
    name: Publish x86 Docker Image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          file: ./platform/docker/Server.x86.Dockerfile
          context: ./platform
          push: true
          tags: ghcr.io/maperz/iot-server

  publish-arm:
    needs: test
    name: Publish ARM Docker Image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          file: ./platform/docker/Server.Arm.Dockerfile
          context: ./platform
          push: true
          tags: ghcr.io/maperz/iot-server/arm
